version: "3.7"

volumes:
  certs-roach-0:
  certs-roach-1:
  certs-roach-2:
  certs-metastore:

services:

##########################################################
# Nifi
##########################################################

  nifi:
    image: apache/nifi:1.9.2
    hostname: nifi
    container_name: nifi
    ports:
      - 9095:9095
    environment:
      NIFI_WEB_HTTP_PORT: 9095
    volumes:
      - ${PWD}/nifi:/opt/nifi/nifi-current/conf/templates
      - ${PWD}/drivers:/opt/nifi/nifi-current/jdbc

##########################################################
# Cockroach DB
##########################################################
  haproxy:
    container_name: haproxy
    hostname: haproxy
    build: haproxy
    ports:
      - "8090:8080"
      - "8091:8081"
      - "5432:5432"
    depends_on:
      - roach-0
      - roach-1
      - roach-2

  roach-cert:
    container_name: roach-cert
    hostname: roach-cert
    build: roach-cert
    volumes:
      - certs-roach-0:/certs/roach-0
      - certs-roach-1:/certs/roach-1
      - certs-roach-2:/certs/roach-2
      - certs-metastore:/certs/metastore

  roach-0:
    container_name: roach-0
    hostname: roach-0
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --insecure --listen-addr=roach-0:26257 --advertise-addr=roach-0:26257
    volumes:
      - certs-roach-0:/certs
      - ${PWD}/sql:/cockroach/sql
    depends_on:
      - roach-cert

  roach-1:
    container_name: roach-1
    hostname: roach-1
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --insecure --join=roach-0 --listen-addr=roach-1:26257 --advertise-addr=roach-1:26257
    volumes:
      - certs-roach-1:/certs
      - ${PWD}/sql:/cockroach/sql
    depends_on:
      - roach-cert
      - roach-0

  roach-2:
    container_name: roach-2
    hostname: roach-2
    image: cockroachdb/cockroach:latest
    command: start --logtostderr=WARNING --insecure --join=roach-0 --listen-addr=roach-2:26257 --advertise-addr=roach-2:26257
    volumes:
      - certs-roach-2:/certs
      - ${PWD}/sql:/cockroach/sql
    depends_on:
      - roach-cert
      - roach-0
      - roach-1
